@startuml
title CJM — Пользователь Авито.Кухня
start

:Пользователь заходит в Авито.Кухню;

partition "Поиск заведения" {
    :Ищет / выбирает заведение;
    :Открывает меню;
}

partition "Просмотр меню" {
    :Выбирает категорию;
    :Просматривает блюда;
}

partition "Корзина" {
    :Добавляет блюдо в корзину;
    :Изменяет количество блюда;
    :Удаляет блюдо из корзины;
    :Открывает корзину;
    :Проверяет состав заказа;
}

partition "Оформление заказа" {
    :Оформляет заказ;
    :Проверка наличия блюд;
    if (Все блюда в наличии?) then (Да)
        :Создать заказ;
    else (Нет)
        :Уведомить пользователя\nо недоступных блюдах;
        :Предложить убрать/заменить\nнедоступные позиции;
        if (Пользователь согласен\nс изменениями?) then (Да)
            :Удалить/заменить недоступные блюда;
            :Обновить состав заказа;
            :Создать заказ;
        else (Нет)
            :Отменить оформление заказа;
            stop
        endif
    endif
}

partition "Мониторинг заказа" {
    :Следит за статусом заказа;
    if (Ресторан принял заказ?) then (Да)
        :Статус: Принят;
        :Статус: Готовится;
        :Статус: Готово;
    else (Нет)
        :Статус: Отклонён;
        :Уведомить пользователя\nоб отклонении заказа;
        stop
    endif
}

:Получает заказ;
stop
@enduml
